### ISSUE TITLE
[SECURITY] Change the default to be secure by default

### ISSUE THREAD

**Issue by JLLeitschuh** [ruby/yaml#11]
Hi!

Security researcher here looking into YAML parsers across the industry. Why is it that this YAML parser is insecure-by-default? Why not make it secure-by-default and then allow end-users to opt-in to the insecure variant similar to how the ruby standard library handles it currently.

**Comment by hsbt** [comment]
?

I didn't understand you say "Why is it that this YAML parser is insecure-by-default?". Please explanation it with Ruby's yaml parser.

**Comment by JLLeitschuh** [comment]
The underlying parser for this gem is using the `unsafe_load` method by default, which has arbitrary deserialization vulnerabilities.

https://github.com/ruby/yaml/blob/a03d8408afe2f5531066887105f95cdb10e136de/lib/yaml/store.rb#L67-L74

There is also the line in the README:

> Do not use YAML to load untrusted data. Doing so is unsafe and could allow malicious input to execute arbitrary code inside your application.

The YAML standard library also has a `safe_load` method, why not use that by-default instead of the insecure variant?

**Comment by hsbt** [comment]
It's only used by `YAML::Store` like `PStore` usage, not the default YAML parser. And There is no reason why it still use `unsafe_load`. I welcome to your pull-request.

**Comment by JLLeitschuh** [comment]
Pull request contributed

**Comment by hsbt** [comment]
I fixed this at #40 and https://github.com/ruby/yaml/pull/41
